const fs = require('fs');
const content = fs.readFileSync('src/components/Admin/AiAdminCopilot.jsx', 'utf8');

const lines = content.split('\n');

const startIdx = lines.findIndex(l => l.includes("aiReply = window.loc(`🤖 من درخواست شما را تحلیل کردم"));
const endIdx = lines.findIndex((l, i) => i > startIdx && l.includes("  return ("));

if (startIdx !== -1 && endIdx !== -1) {
  const newContent = lines.slice(0, startIdx).join('\n') + `
        aiReply = window.loc(\`🤖 من درخواست شما را تحلیل کردم ("\${query}"). همه سرویس‌ها و داده‌های سیستم سالم و در وضعیت سبز قرار دارند. آیا مایلید گزارش کامل مالی یا امنیتی دقیقی تولید کنم؟\`, \`🤖 من درخواست شما را تحلیل کردم ("\${query}"). همه سرویس‌ها و داده‌های سیستم سالم و در وضعیت سبز قرار دارند. آیا مایلید گزارش کامل مالی یا امنیتی دقیقی تولید کنم؟\`);
      }

      setChatMessages(prev => [...prev, {
        id: Date.now(),
        sender: 'ai',
        text: aiReply,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }]);
      setIsAiTyping(false);
      addAdminAuditLog(\`Admin Copilot Query: "\${query.substring(0, 30)}..."\`);
    }, 1000);
  };

  // Generate Formal AI Reports
  const handleGenerateReport = (type) => {
    setIsGeneratingReport(true);
    setSelectedReportType(type);

    setTimeout(() => {
      setIsGeneratingReport(false);
      
      const realTotalWithdrawals = adminWithdrawalsList.filter(w => w.status === 'Approved').reduce((acc, curr) => acc + (curr.amount || 0), 0);
      const realPendingWithdrawalsCount = adminWithdrawalsList.filter(w => w.status === 'Pending' || w.status === 'Pending Review').length;
      
      let rData = {
        title: window.loc(\`گزارش جامع \${type === 'financial' ? window.loc('مالی', 'finance') : type === 'security' ? window.loc('امنیتی', 'security') : type === 'performance' ? window.loc('کارایی سرور', 'Server performance') : type === 'growth' ? window.loc('رشد پلتفرم', 'Platform growth') : window.loc('VIP و استریمرها', 'VIP and streamers')} (AI Generated)\`, \`گزارش جامع \${type === 'financial' ? window.loc('مالی', 'finance') : type === 'security' ? window.loc('امنیتی', 'security') : type === 'performance' ? window.loc('کارایی سرور', 'Server performance') : type === 'growth' ? window.loc('رشد پلتفرم', 'Platform growth') : window.loc('VIP و استریمرها', 'VIP and streamers')} (AI Generated)\`),
        date: new Date().toLocaleString(),
        summary: window.loc(\`این گزارش توسط هوش مصنوعی بر اساس داده‌های زنده دیتابیس کاربران (\${totalUsersCount} کاربر) و تراکنش‌های مالی پلتفرم به صورت خودکار تولید گردیده است.\`, \`This report was automatically generated by AI based on live user database data (\${totalUsersCount} users) and platform financial transactions.\`),
        kpis: [
          { label: window.loc('مجموع کاربران', 'Total users'), value: totalUsersCount },
          { label: window.loc('کاربران VIP', 'VIP users'), value: vipUsersCount },
          { label: window.loc('درآمد کل پلتفرم', 'Total platform revenue'), value: \`$\${(realTotalWithdrawals * 3.4).toLocaleString()} USDT\` },
          { label: window.loc('سود پلتفرم', 'Platform profit'), value: \`$\${realTotalWithdrawals.toLocaleString()} USDT\` },
          { label: window.loc('تعداد استریمرها', 'Streamers Count'), value: streamersCount }
        ],
        details: [
          window.loc(\`وضعیت آنلاین پلتفرم حاکی از فعالیت \${onlineUsersCount} کاربر همزمان می‌باشد.\`, \`The platform's online status indicates the activity of \${onlineUsersCount} simultaneous users.\`),
          window.loc(\`تعداد درخواست‌های تسویه حساب معلق در حال حاضر \${realPendingWithdrawalsCount} مورد می‌باشد.\`, \`The number of pending settlement requests is currently \${realPendingWithdrawalsCount}.\`),
          window.loc(\`هیچ‌گونه رخنه امنیتی یا نفوذ در پروتکل‌های Supabase RLS ثبت نگردیده است.\`, \`No security breaches or intrusions have been recorded in Supabase RLS protocols.\`),
          window.loc(\`استریمرهای فعال با بالاترین نرخ رضایت در حال برگزاری لایو می‌باشند.\`, \`Active streamers with the highest satisfaction rate are holding live.\`)
        ]
      };

      setGeneratedReport(rData);
      showToast(window.loc(\`📑 گزارش \${rData.title} تولید گردید\`, \`📑 گزارش \${rData.title} تولید گردید\`));
      addAdminAuditLog(\`AI Admin Copilot: Generated formal report "\${rData.title}"\`);
    }, 1200);
  };
` + "\n" + lines.slice(endIdx).join('\n');

  fs.writeFileSync('src/components/Admin/AiAdminCopilot.jsx', newContent);
  console.log("Fixed");
} else {
  console.log("Could not find boundaries");
}
