package com.example.util

enum class AppLanguage(val code: String, val label: String) {
    ENGLISH("en", "English 🇺🇸"),
    PERSIAN("fa", "فارسی 🇮🇷")
}

object Strings {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> englishStrings[key] ?: key
            AppLanguage.PERSIAN -> persianStrings[key] ?: (englishStrings[key] ?: key)
        }
    }

    private val englishStrings = mapOf(
        "app_title" to "V.LIVE +18",
        "app_subtitle" to "3D Neon Adult Stream, Video Call & Crypto Earnings",
        "start_live_female_only" to "Start Live / Video Call (Female Host Only)",
        "female_live_rule_notice" to "According to system rules, hosting live streams is restricted to verified female creators.",
        "telegram_ad_title" to "Telegram Ads: VIP 3D Subscription 50% Off",
        "telegram_ad_desc" to "Zero-fee gift transfers and direct HD video calls.",
        "active_streams" to "Active Live Streams & Video Calls",
        "online_count" to "Online",
        "live_3d" to "LIVE 3D",
        "stars_per_min" to "Stars/min",
        "tab_streams" to "Streams",
        "tab_wallet" to "Wallet",
        "tab_profile" to "Profile / VIP",
        "tab_admin" to "Admin & AI",
        "wallet_title" to "V.Live Crypto Wallet",
        "usdt_balance" to "USDT Balance",
        "stars_balance" to "Telegram Stars Balance",
        "quick_topup_50" to "Top Up $50",
        "buy_1000_stars" to "Buy 1000 Stars",
        "withdrawal_section_title" to "Crypto Earnings Payout (Female Hosts Only)",
        "withdrawal_rule_1" to "• Daily withdrawal limit: 1 request per day.",
        "withdrawal_rule_2" to "• 30% admin commission + 1.5 USDT network fee applied on payout.",
        "withdrawal_rule_3" to "• Manual admin approval required for security verification.",
        "withdraw_amount_label" to "Withdrawal Amount (USDT)",
        "wallet_address_label" to "TRC20 / TON Wallet Address",
        "net_payout" to "Net Payout You Receive:",
        "submit_withdrawal" to "Submit USDT Withdrawal Request",
        "withdrawal_history" to "Withdrawal Request History",
        "pending_approval" to "Pending Manual Approval",
        "approved" to "Approved",
        "rejected" to "Rejected",
        "profile_edit_title" to "Edit Account Details",
        "display_name_label" to "Display Name",
        "username_label" to "Telegram/V.Live Username",
        "select_gender" to "Gender Selection (Defines Host Eligibility):",
        "gender_female" to "Female (Allowed to Host Live)",
        "gender_male" to "Male (Viewer Only)",
        "save_profile" to "Save Profile Changes",
        "buy_vip_title" to "Purchase VIP Subscription",
        "buy_with_usdt" to "Purchase with USDT Crypto",
        "admin_panel_title" to "V.Live Admin & AI Anti-Fraud Panel",
        "ai_tab" to "AI & Fraud Protection",
        "withdrawals_tab" to "Pending Withdrawals",
        "ai_engine_title" to "AI Gender & Screen-Recording Protection Engine",
        "block_immediately" to "Block User Immediately",
        "approve_payout" to "Approve & Transfer",
        "reject_request" to "Reject Request",
        "language_switch_title" to "App Language / زبان برنامه",
        "start_live_modal_title" to "Start Live Stream / Video Call",
        "start_live_prompt" to "Enter your neon live title (Face scan and AI gender verification active):",
        "start_live_button" to "Go Live Now",
        "deposit_usdt_title" to "Official Deposit TRC20 USDT Wallet",
        "deposit_address" to "TBMvBiVB6mhu1gnaAAE1Pg5YohKvV1NSnB",
        "copy_address" to "Copy TRC20 Address",
        "daily_gift_title" to "Daily Gift Reward",
        "claim_daily_gift" to "Claim Daily Bonus (+50 Stars)",
        "daily_gift_claimed" to "Daily Bonus Claimed Today!",
        "free_call_quota" to "Daily Free Private Calls (30s each)",
        "free_live_quota" to "Daily Free Live Stream Watching",
        "female_commission_badge" to "40% Commission on Male VIP Purchases Credited to Female Hosts!",
        "host_pricing_controls" to "Host Live & Call Pricing Controls",
        "toggle_free_live" to "Mode: Free Live Stream",
        "toggle_paid_live" to "Mode: VIP Paid Live Stream",
        "set_call_rate" to "Private Call Price (Stars/Min):",
        "live_stream_packages" to "Live Stream Viewing Packages",
        "private_call_packages" to "Private Video Call Packages",
        "buy_package" to "Buy Package Now",
        "super_admin_title" to "Super Admin & Support Login",
        "login_button" to "Login as Super Admin",
        "login_success" to "Logged in as Super Admin (Rayan) - Full Unlimited Access Active!",
        "invalid_credentials" to "Invalid Username or Password!",
        "super_admin_badge" to "SUPER ADMIN (RAYAN) - UNLIMITED ACCESS",
        "harassment_warning_title" to "Anti-Harassment & Safety Warning",
        "harassment_warning_text" to "Warning: Offensive language, harassment, or dangerous behavior will result in an IMMEDIATE PERMANENT BAN. In case of ban, NO REFUNDS will be issued for active subscriptions and your account balance will be revoked.",
        "report_user" to "Report Violation",
        "report_submitted" to "Report submitted to Super Admin for immediate review.",
        "ban_user_button" to "Permanently Ban & Revoke Subscription",
        "user_banned_msg" to "User permanently banned. Subscription revoked with 0 refund.",
        "reports_tab" to "User Reports & Violations",
        "banned_tab" to "Banned Users List",
        "face_match_title" to "AI Profile Photo & Live Stream Verification",
        "face_match_passed" to "Face Verified Match: 98.4% (Authentic Host)",
        "face_match_failed" to "Fraud Warning: Profile Photo Mismatch! Zero Payout Processed.",
        "host_early_disconnect_rule" to "If the female host disconnects the call early, 0 payout is processed.",
        "host_disconnected_no_payout" to "Call disconnected by host! Zero fee charged and no host earnings generated.",
        "rating_dialog_title" to "Rate Stream / Video Call Experience",
        "rating_submit" to "Submit Rating & Review",
        "dissatisfaction_reason_label" to "Please state the reason for dissatisfaction:",
        "app_rules_modal_title" to "Strict V.Live Terms & Anti-Fraud Agreement",
        "rules_accept_button" to "I Have Read & Agree to All Strict Rules",
        "rules_male_title" to "👨 Rules for Male Viewers",
        "rules_male_text" to "1. Absolutely NO harassment, offensive words, or abusive comments.\n2. Any violation results in an IMMEDIATE PERMANENT BAN.\n3. In case of a ban, NO REFUNDS are issued for active subscriptions or token balances.",
        "rules_female_title" to "👩 Rules for Female Hosts",
        "rules_female_text" to "1. Profile photo MUST match live stream face 100%. Fraud/mismatch results in ZERO PAYOUT.\n2. Early disconnection by host voids all earnings for that call.\n3. Abuse or dangerous content leads to immediate permanent ban without payout.",
        "direct_messages_title" to "Private Direct Messages & Support",
        "auto_translate_toggle" to "Auto Chat Translation (EN ↔ FA)",
        "beauty_filter_title" to "Studio Beauty Filter & Lighting FX",
        "security_logs_tab" to "Security Logs & Anti-Screenshot Audit",
        "flag_secure_active" to "FLAG_SECURE Anti-Screenshot Active Across App",
        "vault_title" to "Exclusive Pay-Per-View Media Vault",
        "vault_unlock_button" to "Unlock Media",
        "vault_unlocked" to "Unlocked Media",
        "upload_media_vault" to "Publish Exclusive Media (Female Hosts)",
        "leaderboard_title" to "Weekly Leaderboard & VIP Supporters",
        "top_hosts" to "Top Weekly Female Hosts",
        "top_supporters" to "Top VIP Supporters (Whales)",
        "booking_title" to "1-on-1 Private Call Booking Calendar",
        "book_slot_button" to "Book Private Call",
        "booking_success" to "Private Call Slot Booked Successfully!"
    )

    private val persianStrings = mapOf(

        "app_title" to "V.LIVE +18",
        "app_subtitle" to "تماس تصویری اختصاصی، پخش زنده خانم‌ها و درآمد کریپتویی USDT",
        "start_live_female_only" to "شروع لایو یا تماس تصویری (مخصوص خانم‌ها)",
        "female_live_rule_notice" to "ایجاد لایو و تماس تصویری طبق قوانین فقط برای خانم‌های تایید شده امکان‌پذیر است.",
        "telegram_ad_title" to "تبلیغات تلگرام: اشتراک VIP 3D با ۵۰٪ تخفیف ویژه",
        "telegram_ad_desc" to "ارسال هدایای بدون کارمزد و تماس مستقیم با آیکون اختصاصی",
        "active_streams" to "استریم‌ها و تماس‌های زنده فعال",
        "online_count" to "آنلاین",
        "live_3d" to "پخش زنده ۳ بعدی",
        "stars_per_min" to "Stars/دقیقه",
        "tab_streams" to "استریم‌ها",
        "tab_wallet" to "کیف پول",
        "tab_profile" to "پروفایل / VIP",
        "tab_admin" to "مدیریت و AI",
        "wallet_title" to "کیف پول کریپتو V.Live",
        "usdt_balance" to "موجودی USDT",
        "stars_balance" to "موجودی Stars تلگرام",
        "quick_topup_50" to "شارژ سریع $50",
        "buy_1000_stars" to "خرید 1000 Stars",
        "withdrawal_section_title" to "برداشت درآمد کریپتویی (مخصوص خانم‌ها)",
        "withdrawal_rule_1" to "• امکان برداشت درآمد فقط روزی یک مرتبه مجاز می‌باشد.",
        "withdrawal_rule_2" to "• ۳۰٪ کمیسیون مدیریت + کارمزد بلاکچین (1.5 USDT) هنگام تسویه کسر می‌شود.",
        "withdrawal_rule_3" to "• کلیه برداشت‌ها پس از بررسی و تایید دستی سیستم مدیریت واریز می‌گردد.",
        "withdraw_amount_label" to "مبلغ برداشت به USDT",
        "wallet_address_label" to "آدرس کیف پول TRC20 / TON",
        "net_payout" to "مبلغ دریافتی خالص شما:",
        "submit_withdrawal" to "ثبت درخواست برداشت USDT",
        "withdrawal_history" to "تاریخچه درخواست‌های برداشت",
        "pending_approval" to "در انتظار تایید دستی",
        "approved" to "تایید شده",
        "rejected" to "رد شده",
        "profile_edit_title" to "ویرایش مشخصات حساب کاربری",
        "display_name_label" to "نام نمایشی",
        "username_label" to "نام کاربری Telegram/V.Live",
        "select_gender" to "تعیین جنسیت (جهت دسترسی به لایو خانم‌ها):",
        "gender_female" to "خانم (اجازه گرفتن لایو)",
        "gender_male" to "آقا (تماشاگر)",
        "save_profile" to "ذخیره تغییرات پروفایل",
        "buy_vip_title" to "خرید اشتراک VIP و ویژه",
        "buy_with_usdt" to "خرید اشتراک با کریپتو USDT",
        "admin_panel_title" to "پنل مدیریت و پشتیبانی V.Live",
        "ai_tab" to "هوش مصنوعی و ضدتخلف",
        "withdrawals_tab" to "تایید برداشت‌ها",
        "ai_engine_title" to "موتور هوش مصنوعی تشخیص هویت و ضبط لایو",
        "block_immediately" to "مسدودسازی فوری",
        "approve_payout" to "تایید و واریز",
        "reject_request" to "رد درخواست",
        "language_switch_title" to "App Language / زبان برنامه",
        "start_live_modal_title" to "شروع لایو / تماس تصویری زنده",
        "start_live_prompt" to "عنوان لایو نئونی خود را وارد نمایید (اسکن چهره و هوش مصنوعی فعال است):",
        "start_live_button" to "شروع بث زنده",
        "deposit_usdt_title" to "آدرس رسمی واریز کریپتو TRC20 USDT",
        "deposit_address" to "TBMvBiVB6mhu1gnaAAE1Pg5YohKvV1NSnB",
        "copy_address" to "کپی آدرس TRC20",
        "daily_gift_title" to "هدیه روزانه رایگان",
        "claim_daily_gift" to "دریافت هدیه روزانه (+50 Stars)",
        "daily_gift_claimed" to "هدیه روزانه امروز دریافت شده است!",
        "free_call_quota" to "تماس خصوصی رایگان روزانه آقایان (۳ بار، هر بار ۳۰ ثانیه)",
        "free_live_quota" to "مشاهده لایو زنده رایگان روزانه آقایان (۱۵ دقیقه)",
        "female_commission_badge" to "۴۰٪ از درآمد خرید VIP آقایان مستقیما به حساب خانم‌ها واریز می‌گردد!",
        "host_pricing_controls" to "تنظیمات قیمت‌گذاری لایو و تماس خصوصی خانم‌ها",
        "toggle_free_live" to "حالت: لایو رایگان",
        "toggle_paid_live" to "حالت: لایو VIP پولی",
        "set_call_rate" to "قیمت تماس خصوصی (سکه/دقیقه):",
        "live_stream_packages" to "بسته‌های ویژه تماشای لایو زنده",
        "private_call_packages" to "بسته‌های متنوع تماس تصویری خصوصی",
        "buy_package" to "خرید فوری بسته",
        "super_admin_title" to "ورود مدیریت کل و پشتیبانی (Super Admin)",
        "login_button" to "ورود به عنوان مدیریت کل",
        "login_success" to "ورود موفق به عنوان مدیریت کل (Rayan) - دسترسی نامحدود به تمام امکانات فعال شد!",
        "invalid_credentials" to "نام کاربری یا رمز عبور اشتباه است!",
        "super_admin_badge" to "مدیریت کل (RAYAN) - دسترسی کاملاً نامحدود",
        "harassment_warning_title" to "اخطار مهم عدم توهین و رعایت قوانین",
        "harassment_warning_text" to "اخطار: هرگونه توهین، آزار و اذیت یا محتوای خطرناک موجب مسدودسازی دائمی حساب کاربری می‌شود. در صورت گزارش و مسدودسازی، هیچ وجهی بابت اشتراک فعال مسترد نخواهد شد و اشتراک کلاً غیرفعال و لغو می‌گردد.",
        "report_user" to "گزارش تخلف کاربر",
        "report_submitted" to "گزارش تخلف ثبت شد و جهت بررسی فوری به مدیریت ارسال گردید.",
        "ban_user_button" to "مسدودسازی دائمی و لغو اشتراک بدون استرداد وجه",
        "user_banned_msg" to "کاربر به صورت دائمی مسدود شد و اشتراک وی بدون برگشت وجه غیرفعال گردید.",
        "reports_tab" to "گزارش‌های تخلف کاربران",
        "banned_tab" to "لیست کاربران مسدود شده",
        "face_match_title" to "سیستم هوش مصنوعی تطبیق عکس پروفایل با مجری لایو",
        "face_match_passed" to "تطبیق چهره موفقیت‌آمیز: ۹۸.۴٪ (مجری واقعی و تایید شده)",
        "face_match_failed" to "اخطار تقلب: عکس پروفایل با چهره مجری مطابقت ندارد! هیچ وجهی پرداخت نخواهد شد.",
        "host_early_disconnect_rule" to "در صورت قطع تماس از طرف خانم، هیچ وجهی محاسبه و پرداخت نمی‌گردد.",
        "host_disconnected_no_payout" to "تماس توسط مجری قطع شد! هیچ هزینه‌ای کسر نگردید و درآمدی برای مجری ثبت نشد.",
        "rating_dialog_title" to "امتیازدهی و ثبت نظر تماس / لایو زنده",
        "rating_submit" to "ثبت امتیاز و نظر",
        "dissatisfaction_reason_label" to "لطفاً علت نارضایتی خود را بیان فرمایید:",
        "app_rules_modal_title" to "قوانین بسیار سخت‌گیرانه و توافق‌نامه ضدتخلف V.Live",
        "rules_accept_button" to "تمام قوانین را به طور کامل مطالعه کرده و می‌پذیرم",
        "rules_male_title" to "👨 قوانین و مقررات اختصاصی آقایان (تماشاگران)",
        "rules_male_text" to "۱. هرگونه توهین، الفاظ نامناسب، آزار و اذیت یا مزاحمت اکیداً ممنوع است.\n۲. در صورت کوچک‌ترین گزارش تخلف، حساب شما بدون هیچ تذکری به صورت دائمی مسدود خواهد شد.\n۳. در صورت مسدودسازی به علت تخلف، هیچ وجهی بابت اشتراک فعال یا سکه‌های خریداری شده مسترد نمی‌شود و اشتراک کلاً غیرفعال خواهد شد.",
        "rules_female_title" to "👩 قوانین و مقررات اختصاصی خانم‌ها (مجریان استریم و تماس)",
        "rules_female_text" to "۱. تصویر پروفایل باید ۱۰۰٪ با چهره مجری لایو زنده مطابقت داشته باشد. در صورت تقلب یا استفاده از ویدئوی ضبط شده، هیچ وجهی پرداخت نخواهد شد.\n۲. در صورت قطع تماس از طرف خانم قبل از اتمام زمان استاندارد، هیچ مبلغ یا پاداشی محاسبه و تسویه نمی‌گردد.\n۳. پخش هرگونه محتوای خطرناک یا خلاف مقررات منجر به مسدودسازی فوری و ضبط کامل موجودی کیف پول خواهد شد.",
        "direct_messages_title" to "پیام‌های مستقیم و پشتیبانی اختصاصی",
        "auto_translate_toggle" to "ترجمه خودکار چت (فارسی ↔ انگلیسی)",
        "beauty_filter_title" to "افکت‌های زیبایی استودیو و نورپردازی لایو",
        "security_logs_tab" to "لاگ‌های امنیتی و مانیتورینگ ضداسکرین‌شوت",
        "flag_secure_active" to "سیستم امنیتی FLAG_SECURE فعال است (ممانعت از عکس و فیلمبرداری)",
        "vault_title" to "گالری و آلبوم اختصاصی قفل‌شده (Pay-Per-View Vault)",
        "vault_unlock_button" to "باز کردن قفل آلبوم",
        "vault_unlocked" to "محتوای قفل‌گشایی شده",
        "upload_media_vault" to "انتشار عکس/فیلم اختصاصی جدید (مخصوص مجریان خانم)",
        "leaderboard_title" to "جدول رتبه‌بندی برترین مجریان و حامیان طلایی VIP",
        "top_hosts" to "برترین مجریان هفته (Golden Hosts)",
        "top_supporters" to "برترین حامیان مالی و نهنگ‌ها (VIP Supporters)",
        "booking_title" to "تقویم رزرو زمان تماس تصویری ۱ به ۱ با مجری",
        "book_slot_button" to "رزرو نهایی زمان تماس خصوصی",
        "booking_success" to "زمان تماس تصویری خصوصی با موفقیت رزرو گردید!"
    )
}

