package com.example.util

enum class AppLanguage(val code: String, val label: String) {
    ENGLISH("en", "English"),
    PERSIAN("fa", "English (Global)")
}

object Strings {
    fun get(key: String, lang: AppLanguage): String {
        return englishStrings[key] ?: key
    }

    private val englishStrings = mapOf(
        "app_title" to "V.LIVE +18",
        "app_subtitle" to "3D Neon Stream & Video Calls",
        "start_live_female_only" to "Start Live Stream",
        "female_live_rule_notice" to "Hosting live streams is restricted to verified female creators.",
        "telegram_ad_title" to "VIP 3D Subscription",
        "telegram_ad_desc" to "Zero-fee gifts and direct HD video calls.",
        "active_streams" to "Live Streams & Video Calls",
        "online_count" to "Online",
        "live_3d" to "LIVE 3D",
        "stars_per_min" to "Stars/min",
        "tab_streams" to "Streams",
        "tab_wallet" to "Wallet",
        "tab_profile" to "Profile",
        "tab_admin" to "Admin & AI",
        "wallet_title" to "Crypto Wallet",
        "usdt_balance" to "USDT Balance",
        "stars_balance" to "Stars Balance",
        "quick_topup_50" to "Top Up $50",
        "buy_1000_stars" to "Buy 1000 Stars",
        "withdrawal_section_title" to "Payout Request",
        "withdrawal_rule_1" to "Daily limit: 1 request per day.",
        "withdrawal_rule_2" to "30% commission + 1.5 USDT network fee.",
        "withdrawal_rule_3" to "Manual security verification.",
        "withdraw_amount_label" to "Withdrawal Amount (USDT)",
        "wallet_address_label" to "TRC20 Wallet Address",
        "net_payout" to "Net Payout:",
        "submit_withdrawal" to "Submit Withdrawal",
        "withdrawal_history" to "Payout History",
        "pending_approval" to "Pending Approval",
        "approved" to "Approved",
        "rejected" to "Rejected",
        "profile_edit_title" to "Account Details",
        "display_name_label" to "Display Name",
        "username_label" to "Username",
        "select_gender" to "Gender Selection:",
        "gender_female" to "Female (Host)",
        "gender_male" to "Male (Viewer)",
        "save_profile" to "Save Profile",
        "buy_vip_title" to "VIP Subscription",
        "buy_with_usdt" to "Pay with USDT",
        "admin_panel_title" to "Admin & AI Panel",
        "ai_tab" to "AI & Protection",
        "withdrawals_tab" to "Pending Payouts",
        "ai_engine_title" to "AI & Screen Protection",
        "block_immediately" to "Block User",
        "approve_payout" to "Approve Payout",
        "reject_request" to "Reject Request",
        "language_switch_title" to "Language",
        "start_live_modal_title" to "Start Live Stream",
        "start_live_prompt" to "Enter live stream title:",
        "start_live_button" to "Go Live",
        "deposit_usdt_title" to "TRC20 USDT Deposit Address",
        "deposit_address" to "TBMvBiVB6mhu1gnaAAE1Pg5YohKvV1NSnB",
        "copy_address" to "Copy TRC20 Address",
        "daily_gift_title" to "Daily Bonus",
        "claim_daily_gift" to "Claim +50 Stars",
        "daily_gift_claimed" to "Bonus Claimed Today",
        "free_call_quota" to "Daily Free Calls (30s)",
        "free_live_quota" to "Daily Free Live Watching",
        "female_commission_badge" to "40% Host Pool Share Active",
        "host_pricing_controls" to "Host Rates",
        "toggle_free_live" to "Free Stream Mode",
        "toggle_paid_live" to "Paid VIP Mode",
        "set_call_rate" to "Call Rate (Stars/Min):",
        "live_stream_packages" to "Stream Packages",
        "private_call_packages" to "Video Call Packages",
        "buy_package" to "Buy Package",
        "super_admin_title" to "Super Admin Login",
        "login_button" to "Super Admin Login",
        "login_success" to "Logged in as Super Admin",
        "invalid_credentials" to "Invalid Credentials",
        "super_admin_badge" to "SUPER ADMIN",
        "harassment_warning_title" to "Safety Warning",
        "harassment_warning_text" to "Abusive behavior leads to immediate permanent ban without refund.",
        "report_user" to "Report User",
        "report_submitted" to "Report submitted.",
        "ban_user_button" to "Ban User",
        "user_banned_msg" to "User banned.",
        "reports_tab" to "User Reports",
        "banned_tab" to "Banned List",
        "face_match_title" to "AI Verification",
        "face_match_passed" to "Face Match: 98.4%",
        "face_match_failed" to "Face Mismatch Warning",
        "host_early_disconnect_rule" to "Early host disconnect voids payout.",
        "host_disconnected_no_payout" to "Call disconnected by host.",
        "rating_dialog_title" to "Rate Experience",
        "rating_submit" to "Submit Rating",
        "dissatisfaction_reason_label" to "Reason:",
        "app_rules_modal_title" to "Terms & Rules",
        "rules_accept_button" to "I Agree to Rules",
        "rules_male_title" to "Rules for Viewers",
        "rules_male_text" to "• No abusive behavior or harassment.\n• Violations result in permanent ban.",
        "rules_female_title" to "Rules for Hosts",
        "rules_female_text" to "• Face must match profile.\n• Early disconnection voids call earnings.",
        "direct_messages_title" to "Direct Messages",
        "auto_translate_toggle" to "Auto Translate (EN / FA)",
        "beauty_filter_title" to "Studio Beauty Filter",
        "security_logs_tab" to "Security Audit",
        "flag_secure_active" to "FLAG_SECURE Active",
        "vault_title" to "Media Vault",
        "vault_unlock_button" to "Unlock",
        "vault_unlocked" to "Unlocked",
        "upload_media_vault" to "Publish Media",
        "leaderboard_title" to "Weekly Leaderboard",
        "top_hosts" to "Top Hosts",
        "top_supporters" to "Top Supporters",
        "booking_title" to "Private Call Calendar",
        "book_slot_button" to "Book Slot",
        "booking_success" to "Slot Booked Successfully"
    )
}


